name: C Project CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            target: x86_64-apple-darwin
          - arch: arm64
            target: arm64-apple-darwin

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup
        run: |
          brew install llvm autoconf automake libtool
          ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
          ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"

      - name: Build
        run: make TARGET=${{ matrix.target }}

      - name: Lint
        run: |
          make lint
